### ISSUE TITLE
Where to find and how to restore dqn_speedup model?

### ISSUE THREAD

**Issue by odats** [Shmuma/ptan#24]
I want to train DQN agent and run Pong env to see how the agent plays.

After successful completion 05_new_wrappers.py I can find only event logs files: events.out.tfevents.1556915999.ip-172-31-42-166

Where to find and how to restore dqn_speedup model?

**Comment by Shmuma** [comment]
Save of the neural network is not added in this example, but fairly straightforward thing to do. To get started you can check sample from the book here:
* save code: https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On/blob/master/Chapter06/02_dqn_pong.py#L153
* play code: https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On/blob/master/Chapter06/03_dqn_play.py

**Comment by odats** [comment]
Thank you for the support.
