### ISSUE TITLE
It requires pytorch 1.3.0, but I can't download it

### ISSUE THREAD

**Issue by slaweks17** [Shmuma/ptan#31]
I have 1.3.1 on my computer, ptan this does not work with it. I tried and failed to download 1.3.0 release.  So what to do with my "Deep Reinforcement Learning Hands-on" book?

**Comment by Shmuma** [comment]
Hi!

Could you be more specific about your environment (OS, python version,
output of "pip list" command), which example doesn't werk and error
messages you're getting?

сб, 29 февр. 2020 г., 18:16 slaweks17 <notifications@github.com>:

**Comment by slaweks17** [comment]
HI,
I am using Windows 10.
On https://pytorch.org/get-started/previous-versions/ there is no mention of 1.3 version. They only talk about 1.2. Modifying the supplied command into

conda install pytorch==1.3.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
I am getting in a freshly created conda environment:

(pytorch130) C:\Users\Slawek>conda install pytorch==1.3.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\progs2\Anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\progs2\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\progs2\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\progs2\Anaconda3\lib\site-packages\conda\cli\install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\core\solve.py", line 694, in _add_specs
        ssc.r.find_conflicts(spec_set)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\progs2\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\progs2\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\progs2\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\progs2\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\progs2\Anaconda3\Scripts\conda-script.py install pytorch==1.3.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=pytorch130
                CONDA_EXE=C:\progs2\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\progs2\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\progs2\Anaconda3\envs\pytorch130
    CONDA_PROMPT_MODIFIER=(pytorch130)
         CONDA_PYTHON_EXE=C:\progs2\Anaconda3\python.exe
               CONDA_ROOT=C:\progs2\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Slawek
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\progs2\Anaconda3;C:\progs2\Anaconda3\Library\mingw-w64\bin;C:\progs
                          2\Anaconda3\Library\usr\bin;C:\progs2\Anaconda3\Library\bin;C:\progs2\
                          Anaconda3\Scripts;C:\progs2\Anaconda3\bin;C:\progs2\Anaconda3\envs\pyt
                          orch130;C:\progs2\Anaconda3\envs\pytorch130\Library\mingw-w64\bin;C:\p
                          rogs2\Anaconda3\envs\pytorch130\Library\usr\bin;C:\progs2\Anaconda3\en
                          vs\pytorch130\Library\bin;C:\progs2\Anaconda3\envs\pytorch130\Scripts;
                          C:\progs2\Anaconda3\envs\pytorch130\bin;C:\progs2\Anaconda3\condabin;C
                          :\progs2\Anaconda3;C:\progs2\Anaconda3\Library\mingw-w64\bin;C:\progs2
                          \Anaconda3\Library\usr\bin;C:\progs2\Anaconda3\Library\bin;C:\progs2\A
                          naconda3\Scripts;.;C:\R\R-3.6.1\bin\x64;C:\progs2\oracle_client_19_3;C
                          :\progs2\Rtools\bin;C:\progs2\Rtools\mingw_64\bin;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Program Files
                          (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Program
                          Files\Microsoft MPI\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Syst
                          em32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files
                          (x86)\IntelSWTools\compilers_and_libraries\windows\redist\intel64_win\
                          mkl;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL
                          Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft
                          SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\140\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management
                          Engine Components\IPT;C:\Program Files (x86)\Microsoft SQL
                          Server\150\DTS\Binn;C:\Program Files\Git\cmd;C:\Program
                          Files\CMake\bin;.;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Comm
                          on;C:\progs2\Anaconda3;C:\progs2\Anaconda3\Library\mingw-w64\bin;C:\pr
                          ogs2\Anaconda3\Library\usr\bin;C:\progs2\Anaconda3\Library\bin;C:\prog
                          s2\Anaconda3\Scripts;C:\Users\Slawek\AppData\Local\Microsoft\WindowsAp
                          ps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\140\Tools\PowerShell\Modules\;C:\Program
                          Files\Intel\;C:\Program Files\Intel\Wired Networking\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : pytorch130
    active env location : C:\progs2\Anaconda3\envs\pytorch130
            shell level : 1
       user config file : C:\Users\Slawek\.condarc
populated config files : C:\Users\Slawek\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\progs2\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\progs2\Anaconda3\pkgs
                          C:\Users\Slawek\.conda\pkgs
                          C:\Users\Slawek\AppData\Local\conda\conda\pkgs
       envs directories : C:\progs2\Anaconda3\envs
                          C:\Users\Slawek\.conda\envs
                          C:\Users\Slawek\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

But I tried pip, and it did work! :
pip install torch==1.3.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

So thank you, I will close the issue.

Slawek

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Shmuma** [comment]
Glad it was resolved. As a side note, book examples weren't tested on windows, but I've heard from people that some of them are working fine. 

But to be safe, I'd suggest to use linux (maybe as a virtual machine or in a cloud).

**Comment by slaweks17** [comment]
Hi Max,
Yes, I realize that some examples may not work without modifications, e.g. saving images from the gym, but I am hopeful, as Pytorch works quite well on Windows, most stuff, should work.
BTW, is there any channel to report bugs in the book code?
E.g. in chapter 3,  03_atari_gan.py, line 174 you do
gen_input_v.normal_(0, 1).to(device)
instead of
gen_input_v =gen_input_v.normal_(0, 1).to(device)

Regards,
Slawek


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Shmuma** [comment]
The best place is book's repo: https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition

Cannot promise very fast response, though.

**Comment by slaweks17** [comment]
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Shmuma** [comment]
This particular issue with chapter3 example was just fixed :)

**Comment by slaweks17** [comment]
Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
