### ISSUE TITLE
Which PyTorch version?

### ISSUE THREAD

**Issue by tomekstarfunds** [Shmuma/ptan#33]
I can't instal the package. There's info in requirements that PyTorch 1.0.0 is required. I instal it and get the info in anaconda propmpt that version 1.3.0 is required. Unfortunatelly I can't instal version 1.3.0 because of some conflicts but still not sure if that would resolve the issue.

**Comment by Shmuma** [comment]
Hi!

There is a requirements file (https://github.com/Shmuma/ptan/blob/master/requirements.txt),
it says PyTorch 1.3.0.

If you'll be more specific about the conflicts, I can give more assistance with that.

In general, it is a good idea to use anaconda as an environment manager and install pytorch using anaconda instruction. For example:
```
conda install pytorch==1.3.0 torchvision -c pytorch
```

**Comment by tomekstarfunds** [comment]
Hi!

Thanks. With your commend it works. I was trying to link it with cudatoolkit version and it might have caused the problem.
conda install pytorch==1.3.0 torchvision cudatoolkit=10.2 -c pytorch
