### ISSUE TITLE
Unable to install ptan via pip (old versions of dependencies not available)

### ISSUE THREAD

**Issue by szma** [Shmuma/ptan#37]
Hello,

first of all: thank you so much for your book! It was really a pleasure to read and had the right balance between theory and practical implementation.
I am currently reimplementing some of the chapters. Now I need to run your code (to compare the outcomes to my implementation, I do not use ptan).
PTAN currently needs pytorch==1.3 which is not available via pip. The requirements.txt of the book's repository needs pytorch 0.4.1 which is also not available via pip anymore.

Does anybody has suggestions how I can install ptan currently? Or even better how I am able to run the book's code that uses ptan. In the chapters without ptan it was easily possible to adapt the code to pytorch 1.5.

Thanks in advance!
Markus

**Comment by szma** [comment]
Currently I am able to run the code by changing the requirements.txt to:

```
numpy
atari-py
gym
ptan==0.3
opencv-python==3.4.8.29
scipy
torch==1.5.0
torchvision==0.2.1
tensorboard==1.12.0
pybullet
matplotlib
```

In the code mostly tensorboardX imports have to be changed to 
from torch.utils.tensorboard import SummaryWriter.

**Comment by Shmuma** [comment]
Well, from my perspective, it's not a good idea to use pip for pytorch installing.

 In general, anaconda provides much better alternative already pre-build for most of architectures.  According to their index https://anaconda.org/pytorch/pytorch/files they have all the historical version. So, anaconda is a better way to get your python virtual env.

Blindly upgrading pytorch to a recent version is not a good idea, as it might cause some hidden incompatibilities, which might run ok, but produce totally different results. During preparation of the second edition it was several such cases, so, I recommend to upgrade only if you're brave enough to do a round of troubleshooting the convergence process.
