### ISSUE TITLE
Can not install ptan 

### ISSUE THREAD

**Issue by impedevted** [Shmuma/ptan#39]
Thank you for your book, the way you described let me understand easier on RL algorithm, However, I'm stucking on chapter 07, which using your library(ptan). I install every thing you recommended as below.

conda install pytorch torchvision -c pytorch
pip install tensorboard-pytorch
pip install gym
pip install gym[atari]
pip install opencv-python

and, pip install ptan. the error need torch 1.3.0 but I couldn't the way to install torch 1.3.0 
ERROR: Could not find a version that satisfies the requirement torch==1.3.0 (from ptan) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)ERROR: No matching distribution found for torch==1.3.0 (from ptan)

Is it possible to work with torch 1.5 or other way to install torch 1.3.0?

Thank you

**Comment by Shmuma** [comment]
Hi!

Yes, you can specify torch version on conda install:
`conda install pytorch==1.3.0 torchvision==0.4.1 -c pytorch`

It is not recommended to use more recent pytorch, as newer version wasn't thoroughly tested.
