### ISSUE TITLE
Examples in chapters 8 and 9 don't run

### ISSUE THREAD

**Issue by geverl** [Shmuma/ptan#40]
All of them produce the following error:
Traceback (most recent call last):
  File "04_dqn_noisy_net.py", line 59, in <module>
    common.setup_ignite(engine, params, exp_source, NAME, extra_metrics=('snr_1', 'snr_2'))
  File "/home/asterix/ML/Deep-Reinforcement-Learning-Hands-On-Second-Edition/Chapter08/lib/common.py", line 159, in setup_ignite
    ptan_ignite.EpisodeFPSHandler().attach(engine)
  File "/usr/local/lib/python3.8/dist-packages/ptan-0.6-py3.8.egg/ptan/ignite.py", line 80, in attach
  File "/home/asterix/.local/lib/python3.8/site-packages/ignite/engine/engine.py", line 269, in add_event_handler
    if event_name not in self._allowed_events:
  File "/home/asterix/.local/lib/python3.8/site-packages/ignite/engine/events.py", line 124, in __eq__
    raise NotImplementedError
NotImplementedError

**Comment by Shmuma** [comment]
Hi!

Please provide the list of packages in your environment (`pip freeze`)

**Comment by geverl** [comment]
absl-py==0.9.0
apturl==0.5.2
astroid==2.4.1
atari-py==0.2.6
attrs==19.3.0
autopep8==1.5.3
backcall==0.1.0
bcrypt==3.1.7
bleach==3.1.5
blinker==1.4
Brlapi==0.7.0
cachetools==4.1.0
certifi==2019.11.28
chardet==3.0.4
chrome-gnome-shell==0.0.0
cloudpickle==1.3.0
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
cycler==0.10.0
dbus-python==1.2.16
decorator==4.4.2
defer==1.0.6
defusedxml==0.6.0
distro==1.4.0
distro-info===0.23ubuntu1
duplicity==0.8.12.0
EasyProcess==0.3
entrypoints==0.3
fasteners==0.14.1
future==0.18.2
google-auth==1.14.3
google-auth-oauthlib==0.4.1
grpcio==1.29.0
gym==0.17.2
httplib2==0.14.0
idna==2.8
ignite==1.1.0
imageio==2.8.0
ipykernel==5.2.1
ipython==7.14.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.17.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.1.4
jupyterlab-server==1.1.5
keyring==18.0.1
kiwisolver==1.2.0
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lazy-object-proxy==1.4.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
Markdown==3.2.2
MarkupSafe==1.1.0
matplotlib==3.2.1
mccabe==0.6.1
mistune==0.8.4
monotonic==1.5
nbconvert==5.6.1
nbformat==5.0.6
netifaces==0.10.4
notebook==6.0.3
numpy==1.18.4
oauthlib==3.1.0
olefile==0.46
opencv-python==4.2.0.34
packaging==20.3
pandocfilters==1.4.2
paramiko==2.6.0
parso==0.7.0
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.12.0
ptan==0.6
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycodestyle==2.6.0
pycups==1.9.73
pyglet==1.5.0
Pygments==2.6.1
PyGObject==3.36.0
PyJWT==1.7.1
pylint==2.5.2
pymacaroons==0.13.0
PyNaCl==1.3.0
pyparsing==2.4.7
pyRFC3339==1.1
pyrsistent==0.16.0
python-apt==2.0.0
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
pytorch-ignite==0.4.1
pytz==2019.3
PyVirtualDisplay==0.2.5
pyxdg==0.26
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
reportlab==3.5.34
requests==2.22.0
requests-oauthlib==1.3.0
requests-unixsocket==0.2.0
rsa==4.0
scipy==1.4.1
SecretStorage==2.3.1
Send2Trash==1.5.0
simplejson==3.16.0
six==1.14.0
systemd-python==234
tensorboard==2.2.1
tensorboard-plugin-wit==1.6.0.post3
tensorboard-pytorch==0.7.1
tensorboardX==2.0
terminado==0.8.3
testpath==0.4.4
toml==0.10.1
torch==1.5.0
torchvision==0.6.0
tornado==6.0.4
traitlets==4.3.3
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
wadllib==1.3.3
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
xkit==0.0.0

**Comment by Shmuma** [comment]
Please setup your environment according to `requirements.txt`: https://github.com/Shmuma/ptan/blob/master/requirements.txt

If you're using ptan to make book's examples working, examples' repo has its own set of dependencies: https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/master/requirements.txt

**Comment by geverl** [comment]
I've created a Ubuntu 20.04 VM from scratch and tried to run python3 setup.py install. This fails as it cannot find pytorch 1.3.0.
So I followed your response to one of the issues, i.e. I used conda install pytorch==1.3.0 torchvision==0.4.1 -c pytorch. Here's what this gives me:
conda install pytorch==1.3.0 torchvision==0.4.1 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch==1.3.0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
  - torchvision==0.4.1 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

I tried on an Ubuntu 19.04 with python 3.7 and there it works and there's no need to install Conda. It works fine with pip after installing the required versions of torch and torch-ignite.

You could save the buyers of your book a lot of hassle by either updating the code, so that it works with current Python versions, or at least providing all the information that is needed to run the samples with current Python versions, i.e. that the Python version must be less than 3.8.0a0 and how to downgrade existing Python installations, for instance using pyenv.

Thanks

**Comment by Shmuma** [comment]
Thanks a lot for your suggestions, but python 3.7 requirement is stated in the chapter 2 of the book. It is also noted that conda is much more preferred over plain python venv. In addition, that's not my fault that PyTorch developers removed previous version release from pip - I have no control over this project.

In terms of updating the code: I cannot afford testing full set of examples on every new version of PyTorch which is being released every 2 months. Complete test requires about two weeks of GPU time, not taking into account development time. That's why we have `requirements.txt`, which solve the issue with recent version compatibility. Please, just learn basic python programming standards.

And finally - that's an open source project, if you want something - please do this. Pull requests are always welcomed. 

Thanks.
