### ISSUE TITLE
Not able to run ptan.ignite when custom events inherit from enum.Enum

### ISSUE THREAD

**Issue by demkejon001** [Shmuma/ptan#41]
Whenever I use ptan.ignite and call EpisodeFPSHandler().attach(engine), I get a NotImplementedError:

  File "../common.py", line 159, in setup_ignite
      ptan_ignite.EpisodeFPSHandler().attach(engine)
  File "../venv/lib/python3.6/site-packages/ptan/ignite.py", line 80, in attach
    engine.add_event_handler(EpisodeEvents.EPISODE_COMPLETED, self)
  File "../venv/lib/python3.6/site-packages/ignite/engine/engine.py", line 269, in add_event_handler
    if event_name not in self._allowed_events:
  File "../venv/lib/python3.6/site-packages/ignite/engine/events.py", line 124, in \_\_eq\_\_
    raise NotImplementedError

From what I see, ptan.ignite's custom event classes, EpisodeEvents and PeriodEvents, inherit from enum.Enum and they do get registered to the ignite Engine and they are in the ignite's Engine._allowed_events, however they don't become CallableEventWithFilter objects for some reason. I was able to fix the issue by making the custom event classes inherit from EventEnum in ignite.engine:

from ignite.engine import EventEnum
class EpisodeEvents(EventEnum):
class PeriodEvents(EventEnum):

I don't know why I had the issue, I was wondering if was because of some ignite update or something, but I thought you should know.

Thanks.

**Comment by spikett** [comment]
I had this same issue and concluded that PTAN is written to work with Ignite v0.3 but the latest Ignite is v0.41.  Downgrading to Ignite 0.3 solved it for me.

**Comment by OtwellResearch** [comment]
Had same issue, used same solution as demkejon001. Unfortunately I wasted time figuring it out for myself instead of checking here.... but it was good practice. Given that ignite is in active development, I didn't want to revert.

**Comment by cg31** [comment]
I am using new Ignite, it looks custom events should be inherit from EventEnum:

diff --git a/ptan/ignite.py b/ptan/ignite.py
index 65746f8..17eb11d 100644
--- a/ptan/ignite.py
+++ b/ptan/ignite.py
@@ -5,9 +5,9 @@ from typing import Optional
 from ignite.engine import Engine, State
 from ignite.engine import Events
 from ignite.handlers.timing import Timer
+from ignite.engine.events import EventEnum

-
-class EpisodeEvents(enum.Enum):
+class EpisodeEvents(EventEnum):
     EPISODE_COMPLETED = "episode_completed"
     BOUND_REWARD_REACHED = "bound_reward_reached"
     BEST_REWARD_REACHED = "best_reward_reached"
@@ -103,7 +103,7 @@ class EpisodeFPSHandler:
         self._timer.reset()


-class PeriodEvents(enum.Enum):
+class PeriodEvents(EventEnum):
     ITERS_10_COMPLETED = "iterations_10_completed"
     ITERS_100_COMPLETED = "iterations_100_completed"
     ITERS_1000_COMPLETED = "iterations_1000_completed"

**Comment by Shmuma** [comment]
Fixed with 0.7 release (which supports torch 1.7)
